import React from 'react';
import { FileText, Sparkles, Layers, ListChecks } from 'lucide-react';

export default function MeetingSummary({ summary, keyPoints = [] }) {
  return (
    <div className="space-y-6 animate-fadeIn">
      {/* Executive Summary Card */}
      <section className="p-6 md:p-8 rounded-2xl bg-slate-900/80 border border-slate-800 backdrop-blur-xl shadow-xl space-y-4">
        <div className="flex items-center gap-3 pb-3 border-b border-slate-800/80">
          <div className="w-8 h-8 rounded-lg bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400">
            <Sparkles className="w-4 h-4" />
          </div>
          <div>
            <h3 className="text-base font-bold text-white tracking-tight">Executive Summary</h3>
            <p className="text-xs text-slate-400">Concise overview generated by Gemini Flash</p>
          </div>
        </div>

        <div className="text-slate-300 text-sm leading-relaxed whitespace-pre-line font-normal">
          {summary ? (
            <p className="p-4 rounded-xl bg-slate-950/40 border border-slate-800/60 text-slate-200 leading-7">
              {summary}
            </p>
          ) : (
            <p className="text-slate-500 text-xs italic">No executive summary available for this meeting.</p>
          )}
        </div>
      </section>

      {/* Key Discussion Points Card */}
      <section className="p-6 md:p-8 rounded-2xl bg-slate-900/80 border border-slate-800 backdrop-blur-xl shadow-xl space-y-4">
        <div className="flex items-center justify-between pb-3 border-b border-slate-800/80">
          <div className="flex items-center gap-3">
            <div className="w-8 h-8 rounded-lg bg-sky-500/10 border border-sky-500/20 flex items-center justify-center text-sky-400">
              <Layers className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-base font-bold text-white tracking-tight">Key Discussion Points</h3>
              <p className="text-xs text-slate-400">Primary topics, context, and takeaways</p>
            </div>
          </div>
          <span className="text-xs font-mono px-2.5 py-1 rounded-full bg-slate-800 text-slate-300 border border-slate-700">
            {keyPoints.length} {keyPoints.length === 1 ? 'Point' : 'Points'}
          </span>
        </div>

        {keyPoints && keyPoints.length > 0 ? (
          <ul className="grid grid-cols-1 gap-3 pt-1">
            {keyPoints.map((point, index) => (
              <li 
                key={index}
                className="flex items-start gap-3.5 p-4 rounded-xl bg-slate-950/40 border border-slate-800/60 hover:border-slate-700/80 transition-colors"
              >
                <div className="w-6 h-6 rounded-md bg-sky-500/10 border border-sky-500/20 flex items-center justify-center text-sky-400 text-xs font-mono font-bold shrink-0 mt-0.5">
                  {index + 1}
                </div>
                <span className="text-sm text-slate-200 leading-relaxed">
                  {point}
                </span>
              </li>
            ))}
          </ul>
        ) : (
          <div className="p-6 rounded-xl bg-slate-950/20 border border-dashed border-slate-800 text-center text-slate-500 text-xs italic">
            No specific discussion points recorded.
          </div>
        )}
      </section>
    </div>
  );
}
